name: tierlist
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  get_it: ^7.7.0
  injectable: ^2.4.2
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Food Zone
      fonts:
        - asset: assets/fonts/foodzone.ttf
    - family: Coffee Crafts
      fonts:
        - asset: assets/fonts/coffeecrafts.ttf
    - family: Cafe Francoise
      fonts:
        - asset: assets/fonts/cafefrancoise.otf
    - family: Cartoonist
      fonts:
        - asset: assets/fonts/cartoonist.ttf
    - family: Keep Calm
      fonts:
        - asset: assets/fonts/keepcalm.ttf
    - family: League Spartan
      fonts:
        - asset: assets/fonts/leaguespartan.ttf
    - family: Mouse Memoirs
      fonts:
        - asset: assets/fonts/mousememoirs.ttf
  
