name: tierlist
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  get_it: ^7.7.0
  injectable: ^2.4.2
  dotted_border: ^2.1.0
  zoom_tap_animation: ^1.1.0
  image_picker: ^1.1.2
  crop_your_image: ^1.1.0
  permission_handler: ^11.3.1
  path: ^1.9.0
  path_provider: ^2.1.4
  super_tooltip: ^2.0.9
  image_gallery_saver: '^2.0.3'
  url_launcher: ^6.3.1
  share_plus: ^10.0.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
    - lib/data/sources/images/list_images/
    - lib/data/sources/images/lists/food/
    - lib/data/sources/images/lists/sports/
    - lib/data/sources/images/lists/places/
  fonts:
    - family: Coffee Crafts
      fonts:
        - asset: assets/fonts/coffeecrafts.ttf
  
